[project]
name = "call-me-maybe"
version = "1.0.0"
description = "Function calling with constrained decoding for small LLMs"
requires-python = ">=3.10"
dependencies = [
    "pydantic",
    "numpy",
    "transformers",
    "torch",
    "huggingface_hub",
]

[dependency-groups]
dev = [
    "flake8>=6.0.0",
    "mypy>=1.0.0",
]